### ISSUE TITLE
Operate time machine client with keys

### ISSUE THREAD

**Issue by rsargent** [CMU-CREATE-Lab/breathecam#3]
Current behavior:
- if you focus on the time machine, p toggles play/pause.  Arrows are ignored.
- if you focus on the scrubber, arrows move back and forth frames (but keep playing if playing).  p is ignored

Desired behavior:
- Maybe the scrubber can't be focused.  Or if it is still focusable, same keystroke behavior whether it is or isn't
- If you press p, toggles play/pause
- If you press spacebar, toggles play/pause
- If you press arrow key, pauses video (if not already paused) and moves a frame

**Comment by rsargent** [comment]
This would be super-helpful when scrubbing through lots of video.

**Comment by pdille** [comment]
What behavior should up and down arrows have? Up equivalent to right arrow? And similarly for the down arrow? Or are they ignored?

The current plan is to implement what you outlined in the original post, but also give the ability to translate the viewport if the user is also holding down the shift key. So for example, Shift + left arrow or right arrow would translate horizontally. That way we are not removing a feature that allows for more precise viewport movement.

**Comment by rsargent** [comment]
Some people use up and down arrow keys to scroll the page.  And maybe
someday we'd have another use for up and down in an interface that needed
to do more (like switch layers or something).  So I'm feeling uncertain
about binding up and down to be extra frame forward/backwards.

What would you think of:
left:  pause and move left a frame
right: pause and move right a frame
up and down: let those events propagate up
shift left/right/up/down:  translate viewport

**Comment by pdille** [comment]
Exactly what I had in mind.

**Comment by pdille** [comment]
Addressed in timemachine-viewer commit CMU-CREATE-Lab/timemachine-viewer@fa69997a578ba
